name: ğŸ¥ Deploy Doxygen Documentation
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1
        
      - name: ğŸ³ Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      - name: ğŸ’ƒ Create Redirect HTML
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'docs'
          file: 'index.html'
          content: |
            <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
            <html>
            <head>
              <meta http-equiv=Refresh content="0;url=html/index.html">
            </head>
            </html>
            
      - name: ğŸ¤œ Move Doxyfile
        run: mv  ${{github.workspace}}/build/Doxyfile ${{github.workspace}}
        
      - name: ğŸˆ Create Documentation 
        uses: mattnotmitt/doxygen-action@v1
        
      - name: ğŸš€ Deploy To Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
